FROM elixir:1.10

RUN apt-get update
RUN apt-get install -y build-essential inotify-tools imagemagick ffmpeg

RUN mkdir -p /app
WORKDIR /app

COPY mix* ./
RUN mix local.hex --force && mix local.rebar --force \
    && mix deps.get && mix deps.compile

EXPOSE 4000
