FROM elixir:1.11.0

RUN apt-get update
RUN apt-get install -y build-essential curl git inotify-tools imagemagick ffmpeg

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g yarn

RUN mix local.hex --force && mix local.rebar --force

RUN mkdir -p /app
WORKDIR /app

COPY mix* ./
RUN mix deps.get && mix deps.compile

EXPOSE 4000

CMD ["sleep", "infinity"]
